---
- name: Docker-Compose Deployment
  hosts: all
  run_once: true

  tasks:
  - name: 'Check compose_path and stack_name parameters'
    assert:
      that: 
        - compose_path is defined
        - stack_name is defined

  - name: 'Ensure destination directory exists'
    become: true
    file:
      path: /var/lib/ekara
      state: directory
      mode: 0777

  - name: 'Send compose on target host'
    become: true
    template:
      src: "{{ compose_path }}"
      dest: /var/lib/ekara/docker-compose.yml

  - name: 'Stack deployment'
    become: true
    docker_stack:
      state: present
      name: "{{ stack_name }}"
      compose: /var/lib/ekara/docker-compose.yml
