---
- hosts: ek_role_manager
  run_once: true

  tasks:
  - name: 'Checking component_path, compose_path and stack_name parameters'
    assert:
      that: 
        - component_path is defined
        - compose_path is defined
        - stack_name is defined

  - set_fact:
      ek_stack_dir: "/tmp/ek-{{ stack_name }}-{{ lookup('pipe','date') | to_uuid }}"

  - name: "Deploying {{ stack_name }} stack"
    block:
    - name: "Ensure that temporary directory {{ ek_stack_dir }} exists"
      become: true
      file:
        path: "{{ ek_stack_dir }}"
        state: directory
        mode: 0777

    - name: "Sending component files on a Docker Swarm manager"
      become: true
      template:
        src: "{{ component_path }}/"
        dest: "{{ ek_stack_dir }}/"

    - name: "Executing stack deploy"
      become: true
      docker_stack:
        state: present
        name: "{{ stack_name }}"
        compose: "{{ ek_stack_dir }}/{{ compose_path }}"

    always:
    - name: "Purge temporary directory"
      become: true
      file:
        path: "{{ ek_stack_dir }}"
        state: absent
